arxlang/astx

src/arxast/base.py

* Create a metaclass for AST that will overload `__str__`
* Overload `__str__` and `__repr__` in the AST  class
* ```...```
This PR is a:
About this PR:
```
```

fix: Fix classes output as string

---

.pre-commit-config.yaml
poetry.lock
pyproject.toml
src/astx/__init__.py
src/astx/base.py
src/astx/blocks.py
src/astx/callables.py
src/astx/datatypes.py
src/astx/mixes.py
src/astx/operators.py
src/astx/symbol_table.py
tests/test_blocks.py
tests/test_callables.py
tests/test_datatypes.py

* ```...```
This PR is a:
About this PR:
```
```

feat: Overload DataType operators

---

.releaserc.json

* ```...```
This PR is a:
About this PR:
```
```

fix: Fix release configuration

---

.github/workflows/main.yaml
.makim.yaml
.pre-commit-config.yaml
README.md
src/astx/__init__.py
src/astx/datatypes.py
src/astx/flows.py
src/astx/variables.py
tests/test_base.py
tests/test_callables.py
tests/test_flows.py

* ```...```
This PR is a:
About this PR:
```
```

fix: Refactor Control flow classes and improve Documentation

---

.pre-commit-config.yaml
pyproject.toml
src/astx/__init__.py
src/astx/base.py
src/astx/blocks.py
src/astx/callables.py
src/astx/datatypes.py
src/astx/flows.py
src/astx/mixes.py
src/astx/operators.py
src/astx/symbol_table.py
src/astx/variables.py
tests/test_blocks.py
tests/test_callables.py
tests/test_datatypes.py
tests/test_flows.py

* ```...```
This PR is a:
About this PR:
```
```

feat: Add support for ForRangeLoop and ForCountLoop

---

src/astx/base.py
src/astx/blocks.py
src/astx/callables.py
src/astx/datatypes.py
src/astx/flows.py
src/astx/modifiers.py
src/astx/operators.py
src/astx/variables.py
tests/test_flows.py

* ```...```
This PR is a:
About this PR:
```
```

refactor: Use @public for public classes

---

.pre-commit-config.yaml
poetry.lock
pyproject.toml
src/astx/base.py
src/astx/blocks.py
src/astx/callables.py
src/astx/datatypes.py
src/astx/flows.py
src/astx/mixes.py
src/astx/modifiers.py
src/astx/operators.py
src/astx/symbol_table.py
src/astx/variables.py
tests/test_base.py
tests/test_blocks.py
tests/test_callables.py
tests/test_datatypes.py
tests/test_flows.py
tests/test_operators.py

* ```...```
This PR is a:
About this PR:
```
```

fix: Fix the current configuration and the dependencies' pinning

---

.github/workflows/release.yaml

* ```...```
This PR is a:
About this PR:
```
```

fix: fix documentation release workflow

---

.makim.yaml
conda/dev.yaml
mkdocs.yaml

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: Fix docs generation

---

tests/test_operators.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

test: Add more tests for binary_op

---

.makim.yaml
pyproject.toml
src/astx/base.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: Fix typing issues

---

src/astx/datatypes.py
tests/test_datatypes_boolean.py
tests/test_datatypes_integer_i32.py

This PR creates the LiteralBoolean class, the literal for the Boolean data type.
This PR aims to help solving #20 
I added tests for Boolean datatype. Those are run on CI.
This PR is a:
About this PR:
complexity.
```
```

feat: create LiteralBoolean class

---

.makim.yaml
docs/contributing.md
mkdocs.yaml
poetry.lock
pyproject.toml

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix(docs): Fix contributing guide and getting started tutorial

---

.makim.yaml

- `...`
This PR is a:
About this PR:
complexity.
```
```

docs: Add astx.arxlang.org to CNAME

---

src/astx/base.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

feat: Add structure for output from asciinet approach

---

poetry.lock
pyproject.toml
src/astx/__init__.py
src/astx/base.py
src/astx/blocks.py
src/astx/callables.py
src/astx/datatypes.py
src/astx/flows.py
src/astx/mixes.py
src/astx/modifiers.py
src/astx/operators.py
src/astx/symbol_table.py
src/astx/variables.py
src/astx/viz.py
tests/test_blocks.py
tests/test_callables.py
tests/test_datatypes_boolean.py
tests/test_datatypes_integer_i32.py
tests/test_flows.py
tests/test_operators.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

chore(deps): Update dependencies for development

---

src/astx/base.py
src/astx/variables.py
tests/test_blocks.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: Fix get_struct output

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/docs.yaml
.github/workflows/main.yaml
conda/dev.yaml
mkdocs.yaml
src/astx/__init__.py
src/astx/blocks.py
src/astx/packages.py
tests/test_blocks.py
tests/test_packages.py

This PR aims to add support for new AST nodes: Program, Package, and Target.
The idea is to add full support for AST that IRx needs, so it will not have any custom ASTx there.
- `...`
This PR is a:
About this PR:
complexity.
```
```

feat: Add AST for Program, Package, and Target

---

conda/dev.yaml
conda/release.yaml
docs/api/references.md
docs/api/references.rst
docs/gen_ref_nav.py
mkdocs.yaml
poetry.lock
pyproject.toml
scripts/gen_ref_nav.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

docs: Improve API documentation

---

.github/workflows/main.yaml
.makim.yaml
docs/contributing.md
src/astx/base.py
tests/test_packages.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: Support subscripting to get nodes by index

---

src/astx/__init__.py
src/astx/base.py
src/astx/callables.py
src/astx/datatypes.py
src/astx/flows.py
tests/test_callables.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

feat: Improve FunctionCall and add support for While AST statement

---

src/astx/__init__.py
src/astx/datatypes.py
tests/test_datatypes_integer.py

I have added support for i128 bit but not tests

Adding support for i128

---

poetry.lock

- `...`
This PR is a:
About this PR:
complexity.
```
```

chore(poetry-lock): Update paginate

---

src/astx/__init__.py
src/astx/base.py
src/astx/packages.py
src/astx/transpilers/python.py
tests/test_packages.py
tests/transpilers/test_python.py

This PR adds AliasExpr, ImportStmt and ImportFromStmt. 
This PR is an attempt to solve #87 .
```python
from astx.transpilers import python as astx2py
from astx.packages import (
AliasExpr,
ImportFromStmt,
)
alias3 = AliasExpr(name="path", asname="p")
import_from_stmt = ImportFromStmt(module="os", names=[alias3], level=0)
generator = astx2py.ASTxPythonTranspiler()
generated_code = generator.visit(import_from_stmt)
generated_code
``` 
```python
from astx.packages import (
AliasExpr,
ImportFromStmt,
)
alias3 = AliasExpr(name="path", asname="p")
import_from_stmt = ImportFromStmt(
module="os", names=[alias3], level=0
)
import_from_stmt.get_struct()
import_from_stmt.get_struct(simplified=True)
```
This PR is a:
About this PR:
complexity.
Copy and paste this template for your …

feat:Import statement

---

.github/workflows/docs.yaml
.github/workflows/main.yaml
.github/workflows/release.yaml
.prettierignore
poetry.lock
pyproject.toml

This PR aims to:
- update prettier configuration
- update makim dev dependency
- update CI step for checkout

chore(config): Update prettier config, update makim and CI steps

---

conda/release.yaml
src/astx/__init__.py
src/astx/base.py
src/astx/packages.py
src/astx/transpilers/python.py
tests/test_packages.py
tests/transpilers/test_python.py

This PR adds ImportExpr and ImportFromExpr. 
This PR is an attempt to solve #88  .
```python
from astx import ImportExpr, ImportFromExpr, AliasExpr
from astx.transpilers import python as astx2py
alias1 = AliasExpr(name="pi")
alias2 = AliasExpr(name="sqrt", asname="square_root")
import_expr = ImportExpr([alias1])
import_expr.get_struct()
generator = astx2py.ASTxPythonTranspiler()
generated_code = generator.visit(import_expr)
generated_code
import_from_expr = ImportFromExpr(module="math", names=[alias1, alias2])
import_from_expr.get_struct(simplified=True)
generator = astx2py.ASTxPythonTranspiler()
generated_code = generator.visit(import_from_expr)
generated_code
```
This PR is a:
About this PR:
complexity.
```
```

feat: `ImportExpr` and `ImportFromExpr`

---

.github/workflows/main.yaml
.pre-commit-config.yaml
poetry.lock
pyproject.toml
src/astx/callables.py
src/astx/datatypes.py
src/astx/viz.py

This PR is the first PR that adds missing typechecked.
Next, PR I will add it to the AST class, but it would be a bit more complex, because it will add typechecked to everything, which means that I will need more chanes.

fix: Add missing typechecked

---

tests/transpilers/test_python.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

tests: Improve the tests for the astx python transpiler

---

src/astx/classes.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

imp: Improve the usage of ASTNodes with subtypes

---

pyproject.toml

- `...`
This PR is a:
About this PR:
complexity.
```
```

chore(mypy): Update mypy config

---

README.md

- `...`
This PR is a:
About this PR:
complexity.
```
```

docs: Add badges to the READM.md file

---

src/astx/__init__.py
src/astx/base.py
src/astx/exceptions.py
src/astx/tools/transpilers/python.py
tests/test_exceptions.py
tests/tools/transpilers/test_python.py

This PR creates the `ThrowStmt` class. 
This PR is an attempt to resolve #100 .
New files created:
* `src/astx/exceptions.py`
* `tests/test_exceptions.py`
```python
throw_stmt = astx.ThrowStmt()
throw_stmt
from astx.tools.transpilers import python as astx2py
generator = astx2py.ASTxPythonTranspiler()
generated_code = generator.visit(throw_stmt)
print(generated_code)
```
`raise`
This PR is a:
About this PR:
complexity.
* need to do tests with an expression as input for the `ThrowStmt`.
```
```

feat: create `ThrowStmt` class

---

src/astx/__init__.py
src/astx/base.py
src/astx/exceptions.py
src/astx/tools/transpilers/python.py
tests/test_exceptions.py
tests/tools/transpilers/test_python.py

This PR adds `CatchHandlerStmt` and `ExceptionHandlerStmt` classes. 
This PR is an attempt to resolve #101 , #102 
```python
import astx
def fn_print(
arg: astx.LiteralString,
) -> astx.FunctionCall:
"""Return a FunctionCall to print a string."""
proto = astx.FunctionPrototype(
name="print",
args=astx.Arguments(astx.Argument("_", type_=astx.String())),
return_type=astx.String(),
)
fn = astx.Function(prototype=proto, body=astx.Block())
return astx.FunctionCall(
fn=fn,
args=[arg],
)
try_body = astx.Block()
try_body.append(fn_print(astx.LiteralString(value="passed")))
exception_types = [
astx.Identifier("A"),
astx.Identifier("B")
]
except_body = astx.Block()
except_body.append(fn_print(astx.LiteralString(value="failed")))
handler1 = astx.CatchHandlerStmt(
name=astx.Identifier("e"), …
```

feat: create `CatchHandlerStmt` and `ExceptionHandlerStmt`

---

src/astx/__init__.py
src/astx/base.py
src/astx/exceptions.py
src/astx/tools/transpilers/python.py
tests/test_exceptions.py
tests/tools/transpilers/test_python.py

This PR creates the `FinallyHandlerStmt` classes. 
This PR is an attempt to resolve #103 .
```python
import astx
def fn_print(
arg: astx.LiteralString,
) -> astx.FunctionCall:
"""Return a FunctionCall to print a string."""
proto = astx.FunctionPrototype(
name="print",
args=astx.Arguments(astx.Argument("_", type_=astx.String())),
return_type=astx.String(),
)
fn = astx.Function(prototype=proto, body=astx.Block())
return astx.FunctionCall(
fn=fn,
args=[arg],
)
try_body = astx.Block()
try_body.append(fn_print(astx.LiteralString(value="passed")))
exception_types = [
astx.Identifier("A"),
astx.Identifier("B")
]
except_body = astx.Block()
except_body.append(fn_print(astx.LiteralString(value="failed")))
handler1 = astx.CatchHandlerStmt(
name=astx.Identifier("e"),
types=exception_types, …
```

feat: Create `FinallyHandlerStmt` class

---

src/astx/base.py
src/astx/types/operators.py
tests/test_base.py

- `...`
This PR is a:
About this PR:
complexity.
```
```

fix: Fix ParenthesizedExpr value type

---

docs/conventions.md
mkdocs.yaml

- `...`
Note:
This PR is a:
About this PR:
complexity.
```
```

docs: Add documentation about conventions

---

src/astx/blocks.py
src/astx/exceptions.py
src/astx/flows.py

This pull request adds unique ID to blocks and keys (nodes) for better representation . 
#209
Note:
This PR is a:
About this PR:
complexity.
```
```

Fix Ascii representation

---

.releaserc.json

Fix the release workflow
- `...`
Note:
This PR is a:
About this PR:
complexity.
```
```

fix: Fix the release workflow

---

libs/astx-transpilers/src/astx_transpilers/__init__.py

- `...`
Note:
This PR is a:
About this PR:
complexity.
```
```

fix: Fix the release workflow (2)

---

.github/workflows/main.yaml

- `...`
Note:
This PR is a:
About this PR:
complexity.
```
```

chore: Add support for Windows

---

.github/workflows/main.yaml
poetry.lock
pyproject.toml

- `...`
Note:
This PR is a:
About this PR:
complexity.
```
```

chore: Improve the Windows support

---

libs/astx-transpilers/src/astx_transpilers/python_string.py
libs/astx-transpilers/tests/test_python.py
libs/astx/src/astx/__init__.py
libs/astx/src/astx/base.py
libs/astx/src/astx/callables.py
libs/astx/tests/test_callables.py

Adds `YieldStmt` class and its test cases. 
#177 
- `...`
Note:
This PR is a:
About this PR:
complexity.
```
```

add `YieldStmt` Class

---

libs/astx/src/astx/callables.py

- `...`
Note:
This PR is a:
About this PR:
complexity.
```
```

fix: Fix Comprehension

---

libs/astx/src/astx/base.py

- `...`
Note:
This PR is a:
About this PR:
complexity.
```
```

fix: Fix Comprehension and ComprehensionClause

---

libs/astx-transpilers/src/astx_transpilers/python_string.py
libs/astx-transpilers/tests/test_python.py
libs/astx/src/astx/__init__.py
libs/astx/src/astx/base.py
libs/astx/src/astx/comprehensions.py
libs/astx/tests/test_comprehensions.py

This pull request adds support for SetComprehension in the ASTx framework. It introduces a new AST node for set comprehensions, updates the Python transpiler to handle this node, and includes comprehensive tests to ensure correctness.
run `pytest libs/astx/tests/test_comprehensions.py -v`
`pytest libs/astx-transpilers/tests/test_python.py -v`
Note:
-IMAGE REPRESENTATION
This PR is a:
About this PR:
complexity.
```
```

feat: added Set-Comprehension support

---

.releaserc.json

- `...`
Note:
This PR is a:
About this PR:
complexity.
```
```

fix: Fix semantic release configuration
